### ISSUE TITLE
Unexpected Token on file save

### ISSUE THREAD

**Issue by Nikki1993** [AtomLinter/linter-scss-lint#100]
When I save the .scss file in the atom editor, it throws up error

SyntaxError: /home/nikki/.gem/ruby/2.2.0/bin/scss-lint:2 # ^ Unexpected token ILLEGAL
/home/nikki/.gem/ruby/2.2.0/bin/scss-lint:2
#
^
SyntaxError: Unexpected token ILLEGAL
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:411:25)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.provider.lint (/home/nikki/.atom/packages/linter-sass-lint/lib/main.coffee:39:18)
  at promises.push.Promise.then._this.emitter.emit.linter (/home/nikki/.atom/packages/linter/lib/linter-registry.js:95:28)
  at /home/nikki/.atom/packages/linter/lib/linter-registry.js:94:25
  at Set.forEach (native)
  at LinterRegistry.lint (/home/nikki/.atom/packages/linter/lib/linter-registry.js:92:20)
  at /home/nikki/.atom/packages/linter/lib/linter.coffee:88:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /home/nikki/.atom/packages/linter/lib/editor-linter.js:47:28
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1037:20)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1004:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

But linter itself seems to be working just fine. What's up?

**Comment by SpainTrain** [comment]
on cli can you run `which scss-lint`?

**Comment by Nikki1993** [comment]
yep, gives me

/home/nikki/.gem/ruby/2.2.0/bin/scss-lint

**Comment by SpainTrain** [comment]
Sorry, are you still getting this error?

**Comment by Nikki1993** [comment]
Yes.

**Comment by Nikki1993** [comment]
Every time I save the file, this error pops in atom even though linter, as it seems, works just fine.
