### ISSUE TITLE
Failed to load the linter-scss-lint package

### ISSUE THREAD

**Issue by toddmbloom** [AtomLinter/linter-scss-lint#104]
1. Error message comes up when opening up Atom. 

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11
**Thrown From**: [linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint) package, v2.4.0
### Stack Trace

Failed to load the linter-scss-lint package

```
At Cannot find module 'tmp'

Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tbloom/Google Drive/_appData/_config/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:5:7)
    at Object.<anonymous> (/Users/tbloom/Google Drive/_appData/_config/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "linter-scss-lint": {
    "executablePath": "$HOME/.rvm/gems/ruby-2.2.2@global/bin/scss-lint"
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
bottom-dock, v0.3.5
emmet, v2.3.15
git-diff-details, v0.21.0
linter, v1.11.3
linter-csslint, v1.1.0
linter-manager, v0.2.6
linter-scss-lint, v2.4.0
minimap, v4.16.2
minimap-codeglance, v0.4.5
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-selection, v4.3.1
php-twig, v4.0.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by SpainTrain** [comment]
Can you try on CLI:

```
$ apm remove linter-scss-lint && apm install linter-scss-lint
```

Then restart atom

**Comment by Arcanemagus** [comment]
Closing due to a lack of response.
