### ISSUE TITLE
Error: spawn ENOTDIR even though path to binary is set

### ISSUE THREAD

**Issue by JamesHagerman** [AtomLinter/linter-scss-lint#114]
Hi there,

I'm running Atom 1.3.3 under Ubuntu with the linter-scss-lint package. The linter seems to be working, but it is throwing the following error every time it does so. I'm using RVM and have followed the linter-scss-lint instructions about RVM and have thus set the executable path field to:

```
/home/jamis/.rvm/bin/rvm/bin/atom_sass-lint
```

Any ideas what might be causing this?

```
Error: spawn ENOTDIR
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at /home/jamis/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:86:81
    at _exec (/home/jamis/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:60:10)
    at Object.exec (/home/jamis/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:134:10)
    at /home/jamis/.atom/packages/linter-scss-lint/lib/init.coffee:56:26
    at /home/jamis/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:297:12
    at /home/jamis/.atom/packages/linter-csslint/node_modules/atom-linter/lib/helpers.js:333:16
    at process._tickDomainCallback (node.js:411:9)
```

**Comment by Arcanemagus** [comment]
That path doesn't look correct, since as far as I know there is no Ruby package `atom_sass-lint`. Perhaps you are confusing this package (which is an Atom package) with the Ruby gem `scss_lint`?
