### ISSUE TITLE
Failed to activate the linter-scss-lint package

### ISSUE THREAD

**Issue by rustanacexd** [AtomLinter/linter-scss-lint#119]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint) package, v2.5.1

### Stack Trace

Failed to activate the linter-scss-lint package

```
At Cannot find module 'atom-package-path'

Error: Cannot find module 'atom-package-path'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.install (/Users/rustancorpuz/.atom/packages/linter-php/node_modules/atom-package-deps/lib/main.js:27:12)
    at Object.module.exports.activate (/Users/rustancorpuz/.atom/packages/linter-scss-lint/lib/init.coffee:21:34)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs",
      "php-fmt",
      "linter-csslint",
      "django-atom",
      "django-templates",
      "merge-conflicts",
      "linter-eslint",
      "react",
      "linter-jscs",
      "linter-flake8"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-autocomplete-php, v0.18.7
atom-jinja2, v0.5.0
auto-detect-indentation, v0.4.2
autocomplete-php, v0.3.7
autocomplete-plus, v2.27.1
autocomplete-python, v1.6.1
emmet, v2.4.1
file-icons, v1.6.14
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
jshint, v1.8.3
linter, v1.11.3
linter-php, v1.1.8
linter-scss-lint, v2.5.1
project-manager, v2.7.6
python-tools, v0.6.7
source-preview-babel, v0.1.1

# Dev
No dev packages
```

**Comment by rustanacexd** [comment]
Fixed by - https://github.com/steelbrain/package-deps/pull/31
