### ISSUE TITLE
Error: "scss-lint" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.

### ISSUE THREAD

**Issue by fgpayano** [AtomLinter/linter-scss-lint#127]
```
Error: "scss-lint" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
    at parameters.exit (C:\Users\fgoris\.atom\packages\linter-scss-lint\node_modules\atom-linter\lib\helpers.js:141:25)
    at triggerExitCallback (C:\Users\fgoris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\fgoris\AppData\Local\atom\app-1.5.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment]
Have you installed `scss-lint`?

**Comment by fgpayano** [comment]
Oh, great. Now I installed scss-lint by typing "gem install scss_lint" and works perfectly. Thanks Arcanemagus.

**Comment by Arcanemagus** [comment]
Glad to hear it :wink:.

**Comment by JseMTutungi2001** [comment]
por favor podrian ayudarme con este error, he buscado en internet y no logro solucionarlo y ya he instalado el sass con node.js y otros, y luego lo inclui a la ruta del visual studio code y no me ha funcionado osea se instala pero me sigue apareciendo el mismo error. 
"sass-convert" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable. si por favor podrias ayudarme te lo agradeceria mucho...
