### ISSUE TITLE
Ruby Error "Could not find 'scss-lint' "

### ISSUE THREAD

**Issue by brentonstrine** [AtomLinter/linter-scss-lint#132]
Finally got `scss-lint` installed correctly, and now I'm getting this error when I open `.scss` files. 
```
Error: /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:315:in to_specs': Could not find 'scss-lint' (>= 0) among 24 total gem(s) (Gem::LoadError) Checked in 'GEM_PATH=/Users/user1/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0', executegem envfor more information from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:324:into_spec' from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:64:in gem' from /usr/local/bin/scss-lint:22:in

'
```

```
Error: /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'scss-lint' (>= 0) among 24 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/user1/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:324:in `to_spec'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/bin/scss-lint:22:in `<main>'
    at parameters.exit (/Users/user1/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.js:47:27)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I'm on OSX 10.11.4 so I had to install `scss-lint` in `/usr/local/bin/scss-lint` instead of directly in `/usr/bin`. I've updated the executable path accordingly. Here's some info from my terminal that may be relevant:

```
$: echo $PATH
/usr/local/bin/scss-lint:/Users/user1/maven/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$: which scss-lint
/usr/local/bin/scss-lint
$: ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
$: rvm -v
-bash: rvm: command not found
$: rvm --version
-bash: rvm: command not found
```

**Comment by Arcanemagus** [comment]
If you run `scss-lint` from the terminal do you see the same issue? It looks like however you installed `scss-lint` the version of Ruby that Atom sees can't properly find it.

**Comment by brentonstrine** [comment]
Interesting. 

```
$: scss-lint -v
/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'scss-lint' (>= 0) among 24 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/Users/user1/.gem/ruby/2.0.0:/Library/Ruby/Gems/2.0.0:/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:324:in `to_spec'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/bin/scss-lint:22:in `<main>'
```

**Comment by mvattuone** [comment]
Yep, having this problem too, but only recently has it started. I can run scss-lint from the terminal fine so yeah it must be Atom not being able to find the installed version. But then how should I install it so that Atom can find it?

**Comment by Arcanemagus** [comment]
Atom should be using the version available from your PATH... unless you are on OS X in which case we _try_ to use the correct version but Apple decided that GUI apps don't need a real environment so we are just hacking together a guess as to what it should be.

In either case you should be able to specify the full path to it in your settings.

**Comment by mvattuone** [comment]
Got it -- working now after I ensured that the location was specified in my PATH.

Thank you!

**Comment by Arcanemagus** [comment]
I'm going to mark this as closed as the original filer had an issue in their environment preventing `scss-lint` itself from running.
