### ISSUE TITLE
linter-scss-lint errors within a single project

### ISSUE THREAD

**Issue by DanWebb** [AtomLinter/linter-scss-lint#202]
I have a single (ruby) project where linter-scss-lint fails to work, in all other locations it does work but the other locations are not ruby projects with their own gemfiles.

I currently have my executable path set to `/Users/danwebb/.rvm/gems/ruby-2.3.1/wrappers/scss-lint` I've tried replacing `/wrappers` with `/bin` in that path and tried creating a new scoped wrapper with `rvm wrapper current atom scss-lint` as well re-running `gem install scss_lint` with no luck.

This is the error I receive when editing SCSS files in the one project only, I don't have a great deal of experience with ruby and can't make sense of it, maybe someone here can?
```
/Users/danwebb/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source': uninitialized constant Gem::Source (NameError)
Did you mean?  Gem::Source
	from /Users/danwebb/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:46:in `gem_build_complete_path'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2174:in `missing_extensions?'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1055:in `block in find_active_stub_by_path'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1054:in `each'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1054:in `find'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1054:in `find_active_stub_by_path'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/danwebb/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source'
	from /Users/danwebb/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:35:in `full_gem_path'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:142:in `block in full_require_paths'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:141:in `map'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:141:in `full_require_paths'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1542:in `add_self_to_load_path'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1411:in `activate'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `block in activate_bin_path'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `synchronize'
	from /Users/danwebb/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/danwebb/.rvm/gems/ruby-2.3.1/bin/scss-lint:22:in `<main>'
	from /Users/danwebb/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/danwebb/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by DanWebb** [comment]
Running `gem update bundler` fixes this issue.
