### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kurtschlatzer** [AtomLinter/linter-scss-lint#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint) package, v0.0.14

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/kurtschlatzer/.atom/packages/linter-scss-lint/lib/linter-scss-lint.coffee:32

TypeError: undefined is not a function
  at LinterScssLint.destroy (/Users/kurtschlatzer/.atom/packages/linter-scss-lint/lib/linter-scss-lint.coffee:32:17)
  at LinterView.remove (/Users/kurtschlatzer/.atom/packages/linter/lib/linter-view.coffee:252:7)
  at /Users/kurtschlatzer/.atom/packages/linter/lib/linter-view.coffee:124:8
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/text-editor.js:279:27)
  at TextEditor.module.exports.Model.destroy (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/model.js:45:58)
  at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:444:18)
  at HTMLDivElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:179:22)
  at space-pen-ul.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -8:47.3.0 find-and-replace:show (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
  3x -8:37.9.0 core:backspace (atom-text-editor.editor)
     -7:57.7.0 core:save (atom-text-editor.editor)
  2x -7:28.3.0 core:backspace (atom-text-editor.editor)
     -7:25 core:save (atom-text-editor.editor)
  2x -6:10.6.0 core:backspace (atom-text-editor.editor.mini)
     -5:55 core:save (atom-text-editor.editor)
  4x -5:08.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-spacegray-syntax.theme-one-dark-ui.find-visible)
  2x -4:46.4.0 core:backspace (atom-text-editor.editor.mini)
     -4:36.2.0 core:save (atom-text-editor.editor)
  2x -3:53.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-spacegray-syntax.theme-one-dark-ui.find-visible)
  2x -2:36.3.0 editor:toggle-line-comments (atom-text-editor.editor)
  2x -2:07.8.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-spacegray-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "disabledPackages": [
      "autosave",
      "autoflow",
      "background-tips",
      "autocomplete",
      "welcome",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-toml",
      "metrics",
      "open-on-github",
      "pepper-autocomplete",
      "autocomplete-paths",
      "dash",
      "file-templates",
      "git-log",
      "linter-doiuse",
      "package-list",
      "wordpress-api",
      "timecop",
      "bookmarks",
      "styleguide",
      "feedback",
      "spell-check",
      "wrap-guide",
      "Remote-FTP",
      "autoclose-html",
      "cut-line",
      "lorem-ipsum",
      "w3c-validation",
      "esformatter",
      "linter-tidy",
      "linter-phpcs",
      "linter-csslint",
      "linter-htmlhint",
      "less-autocompile",
      "language-mustache"
    ],
    "projectHome": "/Users/kurtschlatzer/Projects"
  },
  "linter-scss-lint": {
    "scssLintExecutablePath": "/Users/kurtschlatzer/.rvm/gems/ruby-2.2.1/bin"
  }
}
```

### Installed Packages

```coffee
# User
Package-Upgrader, v0.3.1
atom-beautify, v0.24.1
autocomplete-plus, v2.12.0
base16-spacegray-syntax, v0.2.0
editorconfig, v1.0.0
git-history, v2.5.0
indent-guide-improved, v1.1.1
language-generic-config, v0.1.4
language-htaccess, v0.1.1
language-svg, v0.8.0
linter, v0.12.1
linter-jshint, v0.1.2
linter-less, v0.3.1
linter-php, v0.0.12
linter-scss-lint, v0.0.14
open-last-project, v0.4.1
pane-layout-plus, v0.6.7
pretty-json, v0.3.3
sassbeautify, v0.2.0
simple-drag-drop-text, v0.2.2
synced-sidebar, v0.2.3
text-manipulation, v0.6.0
title-case, v0.2.0

# Dev
No dev packages
```

**Comment by Fequois** [comment]
If it helps, this happens to me whenever I close a Sass document/tab.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-scss-lint/pull/58
