### ISSUE TITLE
After updating to 1.0.0, get overall linter error now

### ISSUE THREAD

**Issue by smlombardi** [AtomLinter/linter-scss-lint#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1119:26)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at LinterScssLint.Linter.lintFile (/Users/stevelombardi/.atom/packages/linter/lib/linter.coffee:178:19)
  at /Users/stevelombardi/.atom/packages/linter/lib/linter-view.coffee:163:18
  at Array.forEach (native)
  at /Users/stevelombardi/.atom/packages/linter/lib/linter-view.coffee:162:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "preview-tabs",
      "autocomplete-snippets",
      "gulp-control",
      "SFTP-deployment",
      "autoprefixer",
      "linter-csslint",
      "atom-color-highlight",
      "autocomplete-paths"
    ],
    "themes": [
      "isotope-ui",
      "inspired-github"
    ]
  },
  "linter": {
    "statusBar": "Show all errors",
    "ignoredLinterErrors": [
      "jscs",
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
color-picker, v1.7.0
emmet, v2.3.9
file-icons, v1.5.5
inspired-github, v0.5.2
isotope-ui, v2.3.0
linter, v0.12.3
linter-jscs, v1.11.0
linter-jshint, v0.1.4
linter-jsonlint, v0.1.3
linter-scss-lint, v1.0.0
project-manager, v1.15.5
project-palette-finder, v2.4.17
selection-counter, v0.1.1

# Dev
No dev packages
```

**Comment by smlombardi** [comment]
FYI, just updated to 1.0.1 and issue persists.  Had to disable the scss linter.
