### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by joseluisq** [AtomLinter/linter-scss-lint#64]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint) package, v2.0.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn EACCES
  at exports._errnoException (util.js:734:11)
  at ChildProcess.spawn (child_process.js:1145:11)
  at Object.exports.spawn (child_process.js:977:9)
  at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
  at /Users/joseluis/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:40:30
  at Object.module.exports.Helpers._exec (/Users/joseluis/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:22:16)
  at Object.module.exports.Helpers.exec (/Users/joseluis/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:13:13)
  at Object.provider.lint (/Users/joseluis/.atom/packages/linter-scss-lint/lib/init.coffee:44:24)
  at /Users/joseluis/.atom/packages/linter/lib/editor-linter.coffee:69:26
  at currentLinter (/Users/joseluis/.atom/packages/linter/lib/editor-linter.coffee:68:20)
  at /Users/joseluis/.atom/packages/linter/lib/editor-linter.coffee:82:23
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/joseluis/.atom/packages/linter/lib/editor-linter.coffee:64:26)
  at /Users/joseluis/.atom/packages/linter/lib/editor-linter.coffee:57:27

```

### Commands

```
     -5:43.6.0 core:paste (atom-text-editor.editor.is-focused)
     -5:40.8.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -5:40.8.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -5:40.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:34.1.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -4:07.4.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -4:01.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:53.4.0 core:paste (atom-text-editor#linter-scss-lint.executablePath.editor.mini.is-focused)
  4x -2:38.2.0 core:copy (div.package-readme.native-key-bindings)
     -0:10.3.0 core:paste (atom-text-editor#linter-scss-lint.executablePath.editor.mini.is-focused)
     -0:08.9.0 core:save (atom-text-editor#linter-scss-lint.additionalArguments.editor.mini.is-focused)
     -0:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-babel"
    ]
  },
  "linter-scss-lint": {
    "executablePath": "/usr/bin/scss-lint"
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
angularjs, v0.3.0
atom-beautify, v0.28.8
atom-ternjs, v0.7.1
autocomplete-paths, v1.0.2
color-picker, v2.0.11
docblockr, v0.7.3
editor-stats, v0.17.0
editorconfig, v1.0.1
emmet, v2.3.12
file-icons, v1.6.1
highlight-selected, v0.10.1
language-ini, v1.11.0
language-nginx, v0.5.4
linter, v1.2.4
linter-eslint, v3.0.2
linter-php, v1.0.2
linter-scss-lint, v2.0.0
linter-tidy, v1.0.1
minimap, v4.12.1
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
pigments, v0.9.2
tool-bar, v0.1.8
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by willpracht** [comment]
Happen to install anything along the way with `sudo`?

**Comment by joseluisq** [comment]
Yes, I can't install scss_lint via `gem install scss_lint` without `sudo`

**Comment by steelbrain** [comment]
`EACCESS` is an internal node error, it means that you were either trying to execute a directory, or the executable wasn't marked as an executable or You don't have permission to execute it.
Sorry but that's not really a `linter-scss-lint` thing :)

**Comment by joseluisq** [comment]
@steelbrain yep.
Thanks !
