### ISSUE TITLE
Error Linting

### ISSUE THREAD

**Issue by emaildano** [AtomLinter/linter-scss-lint#67]
The linter is active and enabled but doesn't seem to work. Here are the following required related package versions I have.

`ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`
`Sass 3.4.16 (Selective Steve)`
`apm  1.0.1`
`Atom 1.0.7`

Here's the error message I'm getting when running `Linter: Lint`, it also doesn't run while `.scss` files are open:

```
TypeError: Error linting assets/styles/main.scss: No 'scss-lint' executable specified
TypeError: Error linting assets/styles/main.scss: No 'scss-lint' executable specified
at Object.provider.lint (/Users/danielolson/.atom/packages/linter-scss-lint/lib/init.coffee:56:21)
at Promise.then._this.emitter.emit.linter (/Users/danielolson/.atom/packages/linter/lib/linter-registry.coffee:97:31)
at LinterRegistry.triggerLinter (/Users/danielolson/.atom/packages/linter/lib/linter-registry.coffee:96:14)
at /Users/danielolson/.atom/packages/linter/lib/linter-registry.coffee:84:26
at Array.map (native)
at /Users/danielolson/.atom/packages/linter/lib/linter-registry.coffee:80:36
```

**Comment by anywhim** [comment]
The same issue.

**Comment by anywhim** [comment]
I've solved the problem.
Run `which scss-lint` and paste result to
atom -> packages -> linter-scss-lint -> settings -> executable path

**Comment by tgaeta** [comment]
@anywhim I tried your method; however, I'm still getting the same error:

```shell
Error: env: ruby_executable_hooks: No such file or directory
    at exit (/Users/tonyg/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:72:29)
    at triggerExitCallback (/Users/tonyg/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Users/tonyg/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Users/tonyg/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:166:7)
    at Pipe.close (net.js:464:12)
```

Perhaps mine is a different issue though.

**Comment by emaildano** [comment]
I can get it working in CLI but still not in Atom. Even after updating the executable path using `which scss-lint`.

The error is one in Atom, but it just doesn't do anything after reload and relaunching as-well.

Any other suggestions?

**Comment by willpracht** [comment]
Supposedly updated the `executable_hooks` gem should have fixed it. Unfortunately it does not.

Is there any way to pin a specific version of an Atom package?

**Comment by emaildano** [comment]
Hey Everyone, not sure if this is an issue for me anymore.

It's suddenly working. I haven't edited anything since my last post.

**Comment by emaildano** [comment]
@tgaeta, it looks like your issue may be fixed with an update, mentioned here: http://stackoverflow.com/a/18937094

**Comment by tgaeta** [comment]
@emaildano thank you, sir! i'll check it out.
