### ISSUE TITLE
Error: Executing: scss-lint executable

### ISSUE THREAD

**Issue by CSergienko** [AtomLinter/linter-scss-lint#96]
I'm getting the following error whenever I save a .scss file.

```
Error: Executing: /Users/ChrisSergienko/.rvm/gems/ruby-2.2.0/bin/scss-lint
Error: Executing: /Users/ChrisSergienko/.rvm/gems/ruby-2.2.0/bin/scss-lint
  at exit (/Users/ChrisSergienko/.atom/packages/linter-scss-lint/node_modules/atom-linter/lib/helpers.coffee:32:24)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)
```

I am using ruby-2.2.0 through rvm, and I followed the instructions in the readme on creating a wrapper to get around the ruby environment hooks issue others have experienced. My executable path looks like this: `/Users/ChrisSergienko/.rvm/bin/atom_scss-lint` - I have also tried the version specific approach mentioned, but get the same error.

I have tested and can confirm that scss-lint works fine in the CLI.

The versions I have of things are:
- scss-lint 0.42.2
- atom 1.0.19
- apm 1.0.5
- ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
- rvm 1.26.11

I'm not particularly Node savvy, so the error message is really arcane to me. Can anybody provide me with some direction on how to fix this?

Thanks!

**Comment by SpainTrain** [comment]
I recently added rvm instructions to the readme. Could you try out those directions and see if that clears up your issue?

**Comment by CSergienko** [comment]
I tried every step under that part of the readme before I created this issue. Sadly, nothing worked.

**Comment by SpainTrain** [comment]
Still getting this error?  Not much to go on here, but could you try starting up atom from CLI and see if that changes/fixes the issue?

**Comment by CSergienko** [comment]
I have tried that, but still get the error. Not sure what else to try or what other information I can supply that might help.

**Comment by Willibaur** [comment]
The only way I managed to get rid of that problem is by starting Atom from console which is quit annoying to be honest, it is an indicator that there is a bug somewhere. 
Even though, I think you guys at Atom and linter do a great job for the community
